### PR TITLE
Add labels and annotations to the argument spec

### PR DESCRIPTION
**Pull request by hfrSchmidt**
With this addition we are able to add annotations and labels to a newly created cluster.

### CODE REVIEW

**Comment by seancallaway** [comment]
The documentation should be updated to reflect this. Once that's done, I'll merge it. Seems like a good addition.

**Comment by hfrSchmidt** [comment]
I just updated the README with a more complete example. Is this enough concerning the documentation?

**Comment by hfrSchmidt** [comment]
Did you happen to already have a look at the updated readme?

**Comment by seancallaway** [comment]
That's probably good enough for now. I'll likely do some more documentation changes prior to release.

**Pull request merged**
